// ------------------------------------------------------------------------------
//  <auto-generated>
//    This code was auto-generated by 'com.unity.microsoft.gdk.tools:GdkPlatformSettingsGenerator', version
////    Changes to this file may cause incorrect behavior and will be lost when
//    regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

namespace GdkSample_CloudSaves
{
    public static class GdkPlatformSettings
    {
        public static string gameConfigTitleId = "62ab3c24";
        public static string gameConfigScid = "00000000-0000-0000-0000-000062ab3c24";
    }
}