
using System.Collections.Generic;
using Localization;

public static class Areas
{
    public static readonly Dictionary<Area, string> DiscordNames = new()
    {
        { Area.None, "None" },
        { Area.Village, "Exploring the Village" },
        { Area.Caves, "Spelunking in the Caves"  },
        { Area.Ocean, "Sailing the Ocean" },
        { Area.Jungle, "Traversing the Jungle" },
        { Area.Desert, "Trekking Through the Desert" },
        { Area.Factory, "Powering up the Factory" },
        { Area.Mountain, "Riding Through the Mountain" },
        { Area.Military, "Commiting Warcrimes" },
        { Area.MagiTech, "Playing With Portals" },
    };
    
    // This looks a bit horrendous, I know, but StackExchange offers this input:
    // https://stackoverflow.com/questions/268084/creating-a-constant-dictionary-in-c-sharp
    // It's mostly autogenerated anyway and I find it quite readable, so I think it's fine!
    public static string GetDiscordName(this Area area) 
        => LocalizationLoader.LoadAreaDiscordTranslation(area);
    
    public static readonly Dictionary<Area, string> DisplayNames = new()
    {
        { Area.None, "None" },
        { Area.Village, "Stonybrook Village" },
        { Area.Caves, "Chloro Caves"  },
        { Area.Ocean, "Shifting Seas" },
        { Area.Jungle, "Canopy Town" },
        { Area.Desert, "The Impact Zone" },
        { Area.Factory, "Rocket Factory Center" },
        { Area.Mountain, "Crystal Mines" },
        { Area.Military, "The Flats" },
        { Area.MagiTech, "MRI" },
    };

    public static string GetDisplayName(this Area area)
        => LocalizationLoader.LoadAreaDisplayName(area);
}

public enum Area {
    None,
    Village,
    Caves,
    Ocean,
    Jungle,
    Desert,
    Factory,
    Mountain,
    Military,
    MagiTech
    // Space
}

public enum bottleState { 
    empty, 
    cactus, 
    dirty, 
    clean 
}

public enum MinecartState {
    Empty,
    Crystal,
    Lava,
}