// ------------------------------------------------------------------------------
//  <auto-generated>
//    This code was auto-generated by:
//        'com.unity.microsoft.gdk.tools:GdkPlatformSettingsGenerator'
//
//    Changes to this file may cause incorrect behavior and will be lost when
//    regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;

public static class GdkPlatformSettings
{
    public static string gameConfigTitleId = "FFFFFFFF"; // temporary values! do not commit actual ones probably
    public static string gameConfigScid = "00000000-0000-0000-0000-0000FFFFFFFF";
    [Obsolete("gameConfigSandbox will be removed in future releases. Please do not use.", false)]
    public static string gameConfigSandbox = "";
}
